#include "hardware/pio.h"
#include "hardware/clocks.h"
#include <stdio.h>
#include "audio_i2s.pio.h" // Automatically generated by CMake build system

// Hardware Pin Definitions
#define I2S_BCLK_PIN  13
#define I2S_WS_PIN    14
#define I2S_SD_IN     11
#define I2S_DIN_OUT   12

// Global tracking variables for assigned PIO configurations
static PIO pio_tx = pio0;
static PIO pio_rx = pio1;
static uint sm_tx = 0;
static uint sm_rx = 0;

PIO i2s_get_tx_pio(void) { return pio_tx; }
PIO i2s_get_rx_pio(void) { return pio_rx; }
uint i2s_get_tx_sm(void) { return sm_tx; }
uint i2s_get_rx_sm(void) { return sm_rx; }

void audio_i2s_hardware_init(uint32_t sample_rate) {
    printf("[I2S] Loading TX PIO program for speaker-only validation at %lu Hz...\n", (unsigned long)sample_rate);

    // Speaker validation path: keep the mic RX side disabled so we can confirm the MAX98357A gets a valid TX I2S stream.
    uint offset_tx = pio_add_program(pio_tx, &audio_i2s_tx_program);

    sm_tx = pio_claim_unused_sm(pio_tx, true);
    printf("[I2S] Assigned TX state machine: SM=%u on pio0\n", sm_tx);

    // Configure PIO0 (TX / Speaker Master Engine)
    pio_sm_config c_tx = audio_i2s_tx_program_get_default_config(offset_tx);

    // Assign pin behaviors for TX
    sm_config_set_out_pins(&c_tx, I2S_DIN_OUT, 1);
    sm_config_set_sideset_pins(&c_tx, I2S_BCLK_PIN); // BCLK is pin 0, WS is pin 1 of side-set

    // Configure Serializer Out shift register: MSB-first, Autopull enabled, Threshold = 32 bits
    sm_config_set_out_shift(&c_tx, false, true, 32);

    // Force specific GPIOs into PIO functional mode
    pio_gpio_init(pio_tx, I2S_DIN_OUT);
    pio_gpio_init(pio_tx, I2S_BCLK_PIN);
    pio_gpio_init(pio_tx, I2S_WS_PIN);

    // Set clock directions: PIO pins are driven outputting clocks
    pio_sm_set_consecutive_pindirs(pio_tx, sm_tx, I2S_DIN_OUT, 1, true);
    pio_sm_set_consecutive_pindirs(pio_tx, sm_tx, I2S_BCLK_PIN, 2, true);

    // Calculate precise Audio Clock Division for the speaker master clock.
    uint32_t sys_clk = clock_get_hz(clk_sys);
    float clk_div = (float)sys_clk / (float)(sample_rate * 32 * 2 * 2);
    printf("[I2S] sys_clk=%lu clk_div=%.4f\n", (unsigned long)sys_clk, clk_div);

    sm_config_set_clkdiv(&c_tx, clk_div);

    // Initialize and start the TX path only for the isolated speaker validation.
    pio_sm_init(pio_tx, sm_tx, offset_tx + audio_i2s_tx_offset_entry_point, &c_tx);
    pio_sm_set_enabled(pio_tx, sm_tx, true);
    printf("[I2S] TX state machine enabled; RX intentionally disabled for speaker validation.\n");
}
