#include "i2s_core.h"
#include "hardware/pio.h"
#include "hardware/dma.h"
#include "hardware/irq.h"
#include "hardware/clocks.h"
#include "hardware/gpio.h"
#include <stdio.h>
#include <string.h>

#define I2S_DMA_STALL_TIMEOUT_US 200000ULL
static volatile bool i2s_dma_stalled = false;
static volatile uint64_t last_tx_dma_us = 0;
static volatile uint64_t last_rx_dma_us = 0;

static void i2s_debug_led_stall(const char *channel_name, uint64_t now_us, volatile uint64_t *last_us) {
    uint64_t delta_us = now_us - *last_us;
    if (delta_us > I2S_DMA_STALL_TIMEOUT_US) {
        i2s_dma_stalled = true;
        gpio_put(PICO_DEFAULT_LED_PIN, (now_us / 50000ULL) & 1ULL);
        printf("[I2S] DMA stall on %s: delta=%llu us (threshold=%llu us)\n",
               channel_name,
               (unsigned long long)delta_us,
               (unsigned long long)I2S_DMA_STALL_TIMEOUT_US);
    }
}

extern void audio_i2s_hardware_init(uint32_t sample_rate);
extern PIO i2s_get_tx_pio(void);
extern PIO i2s_get_rx_pio(void);
extern uint i2s_get_tx_sm(void);
extern uint i2s_get_rx_sm(void);

// Explicitly pull in standard PIO programs for I2S assembly instructions
// (Note: In a true SDK environment, these are generated by pioasm from .pio files)
// For compilation completeness, we stub the runtime configuration logic.

static PIO tx_pio = pio0;
static PIO rx_pio = pio1;
static uint tx_sm = 0;
static uint rx_sm = 0;

static int dma_tx_chan;
static int dma_rx_chan;
static bool i2s_initialized = false;

// Ping-Pong Double Buffers to ensure zero data-loss during processing
static int32_t tx_buffers[2][I2S_BUFFER_SIZE];
static int32_t rx_buffers[2][I2S_BUFFER_SIZE];

static volatile uint32_t tx_buf_idx = 0;
static volatile uint32_t rx_buf_idx = 0;

// Internal DMA IRQ Handler
static void i2s_dma_irq_handler() {
    uint64_t now_us = time_us_64();

    // Check TX DMA Channel Interrupt
    if (dma_hw->ints0 & (1u << dma_tx_chan)) {
        dma_hw->ints0 = (1u << dma_tx_chan); // Clear interrupt flag

        if (last_tx_dma_us != 0) {
            i2s_debug_led_stall("TX", now_us, &last_tx_dma_us);
        }
        last_tx_dma_us = now_us;

        // Swap buffers for the next cycle
        tx_buf_idx = 1 - tx_buf_idx;

        // Trigger user callback to populate the newly inactive buffer
        i2s_callback_tx_demanded(tx_buffers[1 - tx_buf_idx], I2S_BUFFER_SIZE);

        // Reconfigure and chain the next DMA block pointer
        dma_channel_hw_addr(dma_tx_chan)->al1_read_addr = (uintptr_t)tx_buffers[tx_buf_idx];
    }

    // Check RX DMA Channel Interrupt
    if (dma_hw->ints0 & (1u << dma_rx_chan)) {
        dma_hw->ints0 = (1u << dma_rx_chan); // Clear interrupt flag

        if (last_rx_dma_us != 0) {
            i2s_debug_led_stall("RX", now_us, &last_rx_dma_us);
        }
        last_rx_dma_us = now_us;

        // Swap buffers for the next cycle
        rx_buf_idx = 1 - rx_buf_idx;

        // Fire callback to instantly parse the raw data just recorded
        i2s_callback_rx_ready(rx_buffers[1 - rx_buf_idx], I2S_BUFFER_SIZE);

        // Reconfigure and point to the fresh empty buffer slice
        dma_channel_hw_addr(dma_rx_chan)->al1_write_addr = (uintptr_t)rx_buffers[rx_buf_idx];
    }
}

void i2s_core_init(void) {
    if (i2s_initialized) {
        printf("[I2S] Already initialized; skipping DMA/PIO setup.\n");
        return;
    }

    memset(tx_buffers, 0, sizeof(tx_buffers));
    memset(rx_buffers, 0, sizeof(rx_buffers));
    tx_buf_idx = 0;
    rx_buf_idx = 0;
    i2s_dma_stalled = false;
    last_tx_dma_us = 0;
    last_rx_dma_us = 0;

    gpio_init(PICO_DEFAULT_LED_PIN);
    gpio_set_dir(PICO_DEFAULT_LED_PIN, GPIO_OUT);
    gpio_put(PICO_DEFAULT_LED_PIN, 0);

    printf("[I2S] Initializing PIO clocking and DMA at %lu Hz...\n", (unsigned long)I2S_SAMPLE_RATE);

    // 1. PIO Engine Configuration Setup
    audio_i2s_hardware_init(I2S_SAMPLE_RATE);
    tx_pio = i2s_get_tx_pio();
    rx_pio = i2s_get_rx_pio();
    tx_sm = i2s_get_tx_sm();
    rx_sm = i2s_get_rx_sm();
    printf("[I2S] PIO config: tx_pio=%p sm=%u rx_pio=%p sm=%u\n", (void *)tx_pio, tx_sm, (void *)rx_pio, rx_sm);

    // 2. Allocate DMA Channels
    dma_tx_chan = dma_claim_unused_channel(true);
    dma_rx_chan = dma_claim_unused_channel(true);
    printf("[I2S] Allocated DMA channels: TX=%d RX=%d\n", dma_tx_chan, dma_rx_chan);

    // 3. Configure TX DMA (Memory to Peripheral)
    dma_channel_config c_tx = dma_channel_get_default_config(dma_tx_chan);
    channel_config_set_transfer_data_size(&c_tx, DMA_SIZE_32);
    channel_config_set_read_increment(&c_tx, true);
    channel_config_set_write_increment(&c_tx, false);
    channel_config_set_dreq(&c_tx, pio_get_dreq(tx_pio, tx_sm, true));

    dma_channel_configure(
        dma_tx_chan, &c_tx,
        &tx_pio->txf[tx_sm], // Write address: PIO FIFO
        tx_buffers[0],        // Read address: Primary buffer
        I2S_BUFFER_SIZE,      // Transfer count
        false                 // Do not start yet
    );

    // 4. Configure RX DMA (Peripheral to Memory)
    dma_channel_config c_rx = dma_channel_get_default_config(dma_rx_chan);
    channel_config_set_transfer_data_size(&c_rx, DMA_SIZE_32);
    channel_config_set_read_increment(&c_rx, false);
    channel_config_set_write_increment(&c_rx, true);
    channel_config_set_dreq(&c_rx, pio_get_dreq(rx_pio, rx_sm, false));

    dma_channel_configure(
        dma_rx_chan, &c_rx,
        rx_buffers[0],        // Write address: Primary buffer
        &rx_pio->rxf[rx_sm], // Read address: PIO FIFO
        I2S_BUFFER_SIZE,      // Transfer count
        false                 // Do not start yet
    );

    // 5. Wire Handlers to RP2350 Nested Vectored Interrupt Controller (NVIC)
    dma_channel_set_irq0_enabled(dma_tx_chan, true);
    dma_channel_set_irq0_enabled(dma_rx_chan, true);
    irq_set_exclusive_handler(DMA_IRQ_0, i2s_dma_irq_handler);
    irq_set_enabled(DMA_IRQ_0, true);

    i2s_initialized = true;
    printf("[I2S] DMA/PIO initialization complete.\n");
}

void i2s_core_start(void) {
    if (!i2s_initialized) {
        printf("[I2S] Start requested before initialization; initializing now.\n");
        i2s_core_init();
    }

    printf("[I2S] Starting I2S TX/RX state machines...\n");

    // Enable state machines synchronously to lock audio phases together.
    // Each PIO instance needs its own mask, since the two state machines live on different PIO blocks.
    pio_enable_sm_mask_in_sync(tx_pio, 1u << tx_sm);
    pio_enable_sm_mask_in_sync(rx_pio, 1u << rx_sm);

    // Fire off both background DMA channels simultaneously
    last_tx_dma_us = time_us_64();
    last_rx_dma_us = time_us_64();
    dma_channel_start(dma_tx_chan);
    dma_channel_start(dma_rx_chan);
    printf("[I2S] DMA TX/RX started.\n");
}

void i2s_core_stop(void) {
    dma_channel_abort(dma_tx_chan);
    dma_channel_abort(dma_rx_chan);
    irq_set_enabled(DMA_IRQ_0, false);
    i2s_dma_stalled = false;
    gpio_put(PICO_DEFAULT_LED_PIN, 0);
}

