#include "i2s_core.h"
#include "hardware/pio.h"
#include "hardware/dma.h"
#include "hardware/irq.h"
#include "hardware/clocks.h"
#include <string.h>

// Explicitly pull in standard PIO programs for I2S assembly instructions
// (Note: In a true SDK environment, these are generated by pioasm from .pio files)
// For compilation completeness, we stub the runtime configuration logic.

static PIO tx_pio = pio0;
static PIO rx_pio = pio1;
static uint tx_sm = 0;
static uint rx_sm = 0;

static int dma_tx_chan;
static int dma_rx_chan;

// Ping-Pong Double Buffers to ensure zero data-loss during processing
static int32_t tx_buffers[2][I2S_BUFFER_SIZE];
static int32_t rx_buffers[2][I2S_BUFFER_SIZE];

static volatile uint32_t tx_buf_idx = 0;
static volatile uint32_t rx_buf_idx = 0;

// Internal DMA IRQ Handler
static void i2s_dma_irq_handler() {
    // Check TX DMA Channel Interrupt
    if (dma_hw->ints0 & (1u << dma_tx_chan)) {
        dma_hw->ints0 = (1u << dma_tx_chan); // Clear interrupt flag
        
        // Swap buffers for the next cycle
        tx_buf_idx = 1 - tx_buf_idx;
        
        // Trigger user callback to populate the newly inactive buffer
        i2s_callback_tx_demanded(tx_buffers[1 - tx_buf_idx], I2S_BUFFER_SIZE);
        
        // Reconfigure and chain the next DMA block pointer
        dma_channel_hw_addr(dma_tx_chan)->al1_read_addr = (uintptr_t)tx_buffers[tx_buf_idx];
    }
    
    // Check RX DMA Channel Interrupt
    if (dma_hw->ints0 & (1u << dma_rx_chan)) {
        dma_hw->ints0 = (1u << dma_rx_chan); // Clear interrupt flag
        
        // Swap buffers for the next cycle
        rx_buf_idx = 1 - rx_buf_idx;
        
        // Fire callback to instantly parse the raw data just recorded
        i2s_callback_rx_ready(rx_buffers[1 - rx_buf_idx], I2S_BUFFER_SIZE);
        
        // Reconfigure and point to the fresh empty buffer slice
        dma_channel_hw_addr(dma_rx_chan)->al1_write_addr = (uintptr_t)rx_buffers[rx_buf_idx];
    }
}

void i2s_core_init(void) {
    // 1. PIO Engine Configuration Setup
    // Initialize PIO state machines for I2S communication protocols.
    // Transmit state machine on pio0, Receive state machine on pio1.
    // Clocks are derived from clk_sys to exactly yield I2S_SAMPLE_RATE.
    
    // 2. Allocate DMA Channels
    dma_tx_chan = dma_claim_unused_channel(true);
    dma_rx_chan = dma_claim_unused_channel(true);
    
    // 3. Configure TX DMA (Memory to Peripheral)
    dma_channel_config c_tx = dma_channel_get_default_config(dma_tx_chan);
    channel_config_set_transfer_data_size(&c_tx, DMA_SIZE_32);
    channel_config_set_read_increment(&c_tx, true);
    channel_config_set_write_increment(&c_tx, false);
    channel_config_set_dreq(&c_tx, pio_get_dreq(tx_pio, tx_sm, true));
    
    dma_channel_configure(
        dma_tx_chan, &c_tx,
        &tx_pio->txf[tx_sm], // Write address: PIO FIFO
        tx_buffers[0],        // Read address: Primary buffer
        I2S_BUFFER_SIZE,      // Transfer count
        false                 // Do not start yet
    );
    
    // 4. Configure RX DMA (Peripheral to Memory)
    dma_channel_config c_rx = dma_channel_get_default_config(dma_rx_chan);
    channel_config_set_transfer_data_size(&c_rx, DMA_SIZE_32);
    channel_config_set_read_increment(&c_rx, false);
    channel_config_set_write_increment(&c_rx, true);
    channel_config_set_dreq(&c_rx, pio_get_dreq(rx_pio, rx_sm, false));
    
    dma_channel_configure(
        dma_rx_chan, &c_rx,
        rx_buffers[0],        // Write address: Primary buffer
        &rx_pio->rxf[rx_sm], // Read address: PIO FIFO
        I2S_BUFFER_SIZE,      // Transfer count
        false                 // Do not start yet
    );
    
    // 5. Wire Handlers to RP2350 Nested Vectored Interrupt Controller (NVIC)
    dma_channel_set_irq0_enabled(dma_tx_chan, true);
    dma_channel_set_irq0_enabled(dma_rx_chan, true);
    irq_set_exclusive_handler(DMA_IRQ_0, i2s_dma_irq_handler);
    irq_set_enabled(DMA_IRQ_0, true);
}

void i2s_core_start(void) {
    // Enable state machines synchronously to lock audio phases together.
    // Each PIO instance needs its own mask, since the two state machines live on different PIO blocks.
    pio_enable_sm_mask_in_sync(tx_pio, 1u << tx_sm);
    pio_enable_sm_mask_in_sync(rx_pio, 1u << rx_sm);

    // Fire off both background DMA channels simultaneously
    dma_channel_start(dma_tx_chan);
    dma_channel_start(dma_rx_chan);
}

void i2s_core_stop(void) {
    dma_channel_abort(dma_tx_chan);
    dma_channel_abort(dma_rx_chan);
    irq_set_enabled(DMA_IRQ_0, false);
}
